import { router } from 'expo-router';
import { Image } from 'expo-image';
import { Pressable, ScrollView, StyleSheet, View, Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useState } from 'react';
import { Text } from '#/components/ui/text';
import { useAuthSession } from '#/core/hooks/useAuthSession';
import { Header } from '#/components/elements/Header';

const C = { red: '#820000', soft: '#F9EEEE', ink: '#191413', muted: '#786E6B', line: '#EDE6E3', paper: '#FBF8F6', white: '#FFF', gold: '#B8960C' };
const options = [{ key: 'metric', title: 'Metric', detail: 'Square metres (m²)' }, { key: 'aana', title: 'Aana · Kattha', detail: 'Traditional land units' }, { key: 'dhur', title: 'Dhur', detail: 'Traditional land unit' }];

export default function AccountSettings() {
  const { session } = useAuthSession(); const p = session?.profile; const [unit, setUnit] = useState('metric');
  const initials = p?.name?.split(/\s+/).slice(0, 2).map((x) => x[0]).join('').toUpperCase() || 'N';
  return <SafeAreaView style={s.safe}><Header style={s.header}><Pressable onPress={() => router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.title}>Account settings</Text><View style={{ width: 28 }} /></Header><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}>
    <View style={s.profileCard}><View style={s.avatarWrap}>{p?.image ? <Image source={{ uri: p.image }} style={s.avatar} contentFit="cover" alt="Profile" /> : <View style={s.avatar}><Text style={s.initials}>{initials}</Text></View>}<Pressable style={s.camera} onPress={() => Alert.alert('Profile picture', 'Photo selection will be available soon.')}><Text style={s.cameraText}>✎</Text></Pressable></View><View style={{ flex: 1 }}><Text style={s.name}>{p?.name || 'Your profile'}</Text><Text style={s.email}>{p?.email || 'Add your account details'}</Text></View></View>
    <Text style={s.section}>ACCOUNT</Text><View style={s.card}><SettingRow title="Name & username" detail={p?.username ? `@${p.username}` : 'Add your name and username'} onPress={() => router.push('/account-settings/edit-profile')} /><SettingRow title="Phone & email" detail={p?.phone || p?.email || 'Add contact details'} onPress={() => router.push('/account-settings/edit-contact')} /><SettingRow title="Password" detail="Keep your account secure" onPress={() => router.push('/account-settings/edit-password')} /></View>
    <Text style={s.section}>PREFERENCES</Text><View style={s.card}><Text style={s.preferenceTitle}>Show property area in</Text><Text style={s.preferenceHint}>Choose the unit format you prefer across Namsari.</Text>{options.map((o) => <Pressable key={o.key} style={s.option} onPress={() => setUnit(o.key)}><View style={[s.radio, unit === o.key && s.radioActive]}>{unit === o.key && <View style={s.dot} />}</View><View><Text style={s.optionTitle}>{o.title}</Text><Text style={s.optionDetail}>{o.detail}</Text></View></Pressable>)}</View>
  </ScrollView></SafeAreaView>;
}
function SettingRow({ title, detail, onPress }: { title: string; detail: string; onPress: () => void }) { return <Pressable style={s.row} onPress={onPress}><View style={{ flex: 1 }}><Text style={s.rowTitle}>{title}</Text><Text style={s.rowDetail}>{detail}</Text></View><Text style={s.chevron}>›</Text></Pressable>; }
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: C.paper }, content: { padding: 20, paddingBottom: 48 }, header: { height: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, back: { fontSize: 38, color: C.ink, lineHeight: 40 }, title: { fontSize: 18, fontWeight: '800', color: C.ink }, profileCard: { flexDirection: 'row', alignItems: 'center', gap: 15, backgroundColor: C.red, borderRadius: 22, padding: 18, marginTop: 15 }, avatarWrap: { position: 'relative' }, avatar: { width: 64, height: 64, borderRadius: 32, backgroundColor: C.white, alignItems: 'center', justifyContent: 'center' }, initials: { color: C.red, fontSize: 22, fontWeight: '900' }, camera: { position: 'absolute', right: -3, bottom: -2, width: 25, height: 25, borderRadius: 13, backgroundColor: C.gold, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: C.red }, cameraText: { color: C.white, fontSize: 13 }, name: { color: C.white, fontSize: 18, fontWeight: '800' }, email: { color: '#EBDDDD', fontSize: 11, marginTop: 3 }, section: { color: C.muted, fontSize: 10, fontWeight: '900', letterSpacing: 1.4, marginTop: 28, marginBottom: 10 }, card: { backgroundColor: C.white, borderRadius: 20, borderWidth: 1, borderColor: C.line, paddingHorizontal: 16 }, row: { minHeight: 70, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: C.line }, rowTitle: { color: C.ink, fontSize: 14, fontWeight: '800' }, rowDetail: { color: C.muted, fontSize: 11, marginTop: 4 }, chevron: { color: C.red, fontSize: 27 }, preferenceTitle: { color: C.ink, fontSize: 15, fontWeight: '800', marginTop: 18 }, preferenceHint: { color: C.muted, fontSize: 11, marginTop: 5, marginBottom: 8 }, option: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 14, borderTopWidth: 1, borderTopColor: C.line }, radio: { width: 21, height: 21, borderRadius: 11, borderWidth: 2, borderColor: '#CFC4C0', alignItems: 'center', justifyContent: 'center' }, radioActive: { borderColor: C.red }, dot: { width: 11, height: 11, borderRadius: 6, backgroundColor: C.red }, optionTitle: { color: C.ink, fontSize: 13, fontWeight: '700' }, optionDetail: { color: C.muted, fontSize: 10, marginTop: 2 } });
